name: MORPHO
channels:
    - defaults
    - conda-forge
dependencies:
    - python
    - pandas=2.0.0
    - glob2=0.7
    - tqdm=4.62.0
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - scipy
    - statsmodels
    - icecream
    - pip
    - pip:
        - plotly
        - xlrd
